name: Build and Release Extension

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.4.0, v1.5.0, etc.
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build extension
      run: npm run build
      
    - name: Create extension package
      run: |
        mkdir -p dist
        cp -r CSS dist/
        cp -r HTML dist/
        cp -r JS/bundle dist/JS/
        cp -r Resources dist/
        cp manifest.json dist/
        cp package.json dist/
        cp README.md dist/
        cd dist
        zip -r ../goonopticon-extension.zip .
        cd ..
        ls -la goonopticon-extension.zip
        
    - name: Verify package creation
      run: |
        if [ ! -f "goonopticon-extension.zip" ]; then
          echo "Error: goonopticon-extension.zip was not created"
          exit 1
        fi
        echo "Package created successfully"
        
    - name: Extract version from package.json
      id: version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=v$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: Goonopticon ${{ steps.version.outputs.tag }}
        body: |
          ## Goonopticon ${{ steps.version.outputs.tag }}
          
          ### What's New
          - Auto-update system
          - Improved sidebar layout
          - Enhanced user experience
          
          ### Installation
          1. Download the `goonopticon-extension.zip` file
          2. Extract the zip file
          3. Open Chrome/Edge and go to `chrome://extensions/`
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
          
          ### Files
          - `goonopticon-extension.zip` - Complete extension package
        files: goonopticon-extension.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
